---
version: "3"
services:
  uetomae-tools-migrate:
    image: $CONTAINER_IMAGE:$RAILS_ENV
    command: ['./bin/increment-db']
    environment:
      RAILS_ENV: $RAILS_ENV
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      YAHOO_API_CLIENT_ID: $YAHOO_API_CLIENT_ID
      ROLLBAR_ACCESS_TOKEN: $ROLLBAR_ACCESS_TOKEN
    logging:
      driver: awslogs
      options:
        awslogs-region: $AWS_REGION
        awslogs-group: $LOG_GROUP
        awslogs-stream-prefix: ecs
