#!/bin/sh

PROJECT_DIR=$(cd $(dirname $0); cd ..; pwd)
AWS_CREDENTIALS="$PROJECT_DIR/.awscredentials"

. $PROJECT_DIR/expd-bin/generate-base

# Load existing credential
[ -f "$AWS_CREDENTIALS" ] && source "$AWS_CREDENTIALS"

echo "Enter aws credentials for provisioning"
ask "AWS_ACCESS_KEY_ID" "AWS access key"
ask "AWS_SECRET_ACCESS_KEY" "AWS secret access key"
ask "AWS_DEFAULT_REGION" "AWS region"

echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > $AWS_CREDENTIALS
echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $AWS_CREDENTIALS
echo "export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> $AWS_CREDENTIALS
